spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mysqldemo
    username: root
    password: z13669693494l

mybatis:
  configLocations: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
