spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/mysqldemo?characterEncoding=utf-8&useSSL=false&serverTimezone=CTT
    username: root
    password: z13669693494l
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 50
      minimum-idle: 10
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1765000
      connection-init-sql: 'set names utf8mb4;'

mybatis:
  configLocation: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
